name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build with dumi
        run: npm run build

      - name: Deploy
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.ftp_server }}
          user: owladmin
          password: ${{ secrets.ftp_password }}
          localDir: "dist"
          remoteDir: "docs"
#          options: "--delete --asci"
