name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies .
        run: npm install

      - name: Build with dumi
        run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_server }}
          username: owladmin
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: ./docs/
          dangerous-clean-slate: true
