name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.server_host }}
          user: ${{ secrets.server_user }}
          pass: ${{ secrets.server_pwd }}
          port: ${{ secrets.server_port }}
          connect_timeout: 10s
          first_ssh: |
            mkdir -p /www/wwwroot/admin/docs_new
          scp: |
            './dist/*' => /www/wwwroot/admin/docs_new/
          last_ssh: |
            rm -rf /www/wwwroot/admin/docs
            mv /www/wwwroot/admin/docs_new /www/wwwroot/admin/docs
            rm -rf /www/wwwroot/admin/docs_new
            chown -R www:www /www/wwwroot/admin/docs
            chmod -R 755 /www/wwwroot/admin/docs
