name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build with dumi
        run: npm run build

      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.server_host }}
          user: ${{ secrets.server_user }}
          pass: ${{ secrets.server_pwd }}
          port: ${{ secrets.server_port }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf /www/wwwroot/admin/docs
          scp: |
            './dist/*' => /www/wwwroot/admin/docs/
