name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Install dependencies
#        run: npm install
#
#      - name: Build with dumi
#        run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://47.242.69.232:21
          username: owladmin
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./docs
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
